version: '3.3'

services:
  api:
    build:
      context: ./../..
      dockerfile: docker/prod-setup/dockerfile
    env_file:
      - secrets.env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=mysqldb
      - DB_USER=root
      - DB_PASSWORD=rootpwd
    labels:
      - "traefik.backend=hello-nest"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:hello-nest.example.com"
      - "traefik.enable=true"
      - "traefik.port=3000"
    ports:
      - 3001:3000
    networks:
      - internal-net
      - traefik
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpwd
    networks:
      - internal-net
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./data/backup:/backup
    restart: unless-stopped
networks:
  internal-net:
  traefik:
    external: true
