# TODO: Mulit stage build could reduce the docker file size further

FROM node:11

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]