version: '3.3'

services:
  traefik:
    image: traefik:1.7-alpine
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8081:8080
    networks:
      traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme:/traefik/acme
    restart: unless-stopped
networks:
  traefik:
    external: true
