debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = false

[api]
entryPoint = "traefik"
dashboard = true

# Activate this for performance monitoring of our web apps
#[metrics]
#  [metrics.prometheus]
#    entryPoint = "traefik"
#    buckets = [0.1,0.3,1.2,5.0]

[acme]
email = "me@example.com"
storage = "traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
